import fs from 'node:fs';
import path from 'node:path';

/**
 * The filesystem IS the information architecture.
 *
 * `src/content/docs/` holds one directory per section, named `<order>-<slug>`
 * (e.g. `2-data-structures`). Each carries a `_section.json` describing itself.
 * Everything else — the sidebar, the homepage grid, the per-section index pages —
 * is derived from that. Adding a topic is one new `.mdx` file; adding a whole
 * section is one new directory. Neither requires touching a config file.
 */

/**
 * Resolved from the project root, NOT from `import.meta.url`. This module gets
 * bundled by Vite when a page imports it, at which point the module URL points
 * into the build output and any relative path silently resolves to nothing.
 * `astro dev` and `astro build` both run with cwd at the project root.
 */
const DOCS_DIR = path.resolve(process.cwd(), 'src/content/docs');

export interface SectionMeta {
  /** Directory name, e.g. `2-data-structures` — also the URL segment. */
  dir: string;
  /** Numeric prefix, used for ordering. */
  order: number;
  /** Slug without the numeric prefix, e.g. `data-structures`. */
  slug: string;
  label: string;
  description: string;
  /** Emoji or short glyph shown on section cards. */
  icon?: string;
}

interface SectionJson {
  label: string;
  description: string;
  icon?: string;
}

const SECTION_DIR_PATTERN = /^(\d+)-(.+)$/;

/**
 * Read every section directory under `src/content/docs/`, ordered by numeric prefix.
 *
 * Runs at config/build time only (it touches the filesystem synchronously), which
 * is why it lives here rather than in a component.
 */
export function readSections(): SectionMeta[] {
  // Never return [] quietly. An empty result here means "the site has no
  // content", which renders as a plausible-looking but entirely blank site.
  if (!fs.existsSync(DOCS_DIR)) {
    throw new Error(
      `Content directory not found: ${DOCS_DIR}. ` +
        `readSections() resolves from process.cwd() (${process.cwd()}), so this ` +
        `usually means a tool was run from outside the project root.`,
    );
  }

  const sections = fs
    .readdirSync(DOCS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .flatMap((entry) => {
      const match = SECTION_DIR_PATTERN.exec(entry.name);
      if (!match) return [];

      const metaPath = path.join(DOCS_DIR, entry.name, '_section.json');
      if (!fs.existsSync(metaPath)) {
        throw new Error(
          `Section directory "${entry.name}" is missing _section.json. ` +
            `Every section needs one: { "label": …, "description": …, "icon"?: … }`,
        );
      }

      const meta = JSON.parse(fs.readFileSync(metaPath, 'utf8')) as SectionJson;
      return [
        {
          dir: entry.name,
          order: Number(match[1]),
          slug: match[2],
          label: meta.label,
          description: meta.description,
          icon: meta.icon,
        },
      ];
    })
    .sort((a, b) => a.order - b.order);

  if (sections.length === 0) {
    throw new Error(
      `No section directories found in ${DOCS_DIR}. ` +
        `Sections are directories named "<order>-<slug>", e.g. "2-data-structures".`,
    );
  }

  return sections;
}

/** Does this section have at least one page? Empty dirs break `autogenerate`. */
function hasPages(dir: string): boolean {
  const full = path.join(DOCS_DIR, dir);
  return fs
    .readdirSync(full)
    .some((f) => (f.endsWith('.mdx') || f.endsWith('.md')) && !f.startsWith('_'));
}

/**
 * Build Starlight's `sidebar` config. Each section becomes a collapsible group
 * whose pages are autogenerated from the directory; page order within a group
 * comes from each page's `sidebar.order` frontmatter (set from `order`).
 *
 * Sections with no pages yet are omitted rather than rendered as empty groups —
 * sections 3–6 are scaffolded well before they have content.
 */
export function buildSidebar() {
  return readSections()
    .filter((section) => hasPages(section.dir))
    .map((section) => ({
      label: section.label,
      collapsed: false,
      // Since Starlight v0.39 the autogenerate config nests inside `items`;
      // a group with a top-level `autogenerate` is rejected at config time.
      items: [{ autogenerate: { directory: section.dir } }],
    }));
}
