apiVersion: v1
kind: Pod
metadata:
  name: oomkill-demo
spec:
  containers:
    - name: hog
      image: node:24-slim
      command:
        [
          'node',
          '-e',
          'let x=[]; setInterval(()=>{ x.push(Buffer.alloc(10*1024*1024)); }, 100);',
        ]
      resources:
        limits:
          memory: '50Mi'
        requests:
          memory: '50Mi'
  restartPolicy: Never
