apiVersion: v1
kind: Pod
metadata:
  name: pending-demo
spec:
  containers:
    - name: impossible
      image: nginx:alpine
      resources:
        requests:
          cpu: '999'
          memory: '999Gi'
  restartPolicy: Never
