import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { chromium } from '@playwright/test';
import sharp from 'sharp';

const PORT = 4322;
const BASE = `http://localhost:${PORT}/cs-fundamentals`;
const OUT = 'docs/media';

async function waitForServer(url: string, timeoutMs: number) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(url);
      if (res.ok) return;
    } catch {
      // not up yet
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error(`server did not start: ${url}`);
}

async function main() {
  await mkdir(OUT, { recursive: true });

  const server = spawn('pnpm', ['exec', 'astro', 'preview', '--port', String(PORT)], {
    stdio: 'inherit',
    detached: true,
  });
  const stop = () => {
    try {
      process.kill(-server.pid!, 'SIGKILL');
    } catch {
      // already gone
    }
  };
  process.on('exit', stop);

  try {
    await waitForServer(`${BASE}/`, 60_000);
    console.log('server up');

    const browser = await chromium.launch();
    const page = await browser.newPage({
      viewport: { width: 1280, height: 800 },
      deviceScaleFactor: 2,
      colorScheme: 'dark',
    });

    console.log('capturing site screenshot');
    await page.goto(`${BASE}/2-data-structures/binary-trees/`, {
      waitUntil: 'domcontentloaded',
    });
    await page.addStyleTag({ content: '*{scroll-behavior:auto!important}' });
    await page.waitForTimeout(1500);
    const shot = await page.screenshot({
      clip: { x: 0, y: 0, width: 1280, height: 720 },
    });
    await sharp(shot).resize(1200).webp({ quality: 72 }).toFile(`${OUT}/site.webp`);

    console.log('capturing widget steps');
    await page.goto(`${BASE}/2-data-structures/binary-trees/`, {
      waitUntil: 'domcontentloaded',
    });
    await page.addStyleTag({
      content:
        '*{transition:none!important;animation:none!important}header.header{display:none!important}',
    });

    const figure = page.locator('figure.viz-frame').first();
    await figure.scrollIntoViewIfNeeded();
    const nextStep = figure.getByRole('button', { name: 'Next step' });
    await nextStep.waitFor({ state: 'visible', timeout: 15_000 });
    await page.waitForTimeout(600);

    const stepThroughVisual = figure.locator('.viz-stack').first();

    const frames: Buffer[] = [await stepThroughVisual.screenshot()];
    for (let i = 0; i < 11; i++) {
      await nextStep.click();
      await page.waitForTimeout(350);
      frames.push(await stepThroughVisual.screenshot());
    }
    console.log(`got ${frames.length} frames`);

    await browser.close();

    const held = [frames[0]!, ...frames, frames.at(-1)!, frames.at(-1)!];
    const width = 460;
    const pages = await Promise.all(
      held.map((f) =>
        sharp(f)
          .resize(width)
          .ensureAlpha()
          .raw()
          .toBuffer({ resolveWithObject: true }),
      ),
    );
    const pageHeight = pages[0]!.info.height;
    await sharp(Buffer.concat(pages.map((p) => p.data)), {
      raw: { width, height: pageHeight * held.length, channels: 4 },
      animated: true,
    })
      .gif({ loop: 0, delay: 600, colours: 128, dither: 0.6 })
      .toFile(`${OUT}/widget.gif`);
  } finally {
    stop();
  }

  await writeFile(
    `${OUT}/README.md`,
    'Generated by `pnpm readme:media`. Do not edit by hand.\n',
  );
  console.log('done');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
