import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { chromium } from '@playwright/test';
import sharp from 'sharp';

const PORT = 4322;
const BASE = `http://localhost:${PORT}/cs-fundamentals`;
const OUT = 'docs/media';

async function waitForServer(url: string, timeoutMs: number) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(url);
      if (res.ok) return;
    } catch {
      // not up yet
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error(`server did not start: ${url}`);
}

async function main() {
  await mkdir(OUT, { recursive: true });

  const server = spawn('pnpm', ['exec', 'astro', 'preview', '--port', String(PORT)], {
    stdio: 'inherit',
    detached: true,
  });
  const stop = () => {
    try {
      process.kill(-server.pid!, 'SIGKILL');
    } catch {
      // already gone
    }
  };
  process.on('exit', stop);

  try {
    await waitForServer(`${BASE}/`, 60_000);
    console.log('server up');

    const browser = await chromium.launch();
    const page = await browser.newPage({
      viewport: { width: 1280, height: 800 },
      deviceScaleFactor: 2,
      colorScheme: 'dark',
    });

    console.log('capturing site screenshot');
    await page.goto(`${BASE}/2-data-structures/binary-trees/`, {
      waitUntil: 'domcontentloaded',
    });
    await page.addStyleTag({ content: '*{scroll-behavior:auto!important}' });
    await page.waitForTimeout(1500);
    const shot = await page.screenshot({
      clip: { x: 0, y: 0, width: 1280, height: 720 },
    });
    await sharp(shot).resize(1200).webp({ quality: 72 }).toFile(`${OUT}/site.webp`);

    console.log('capturing widget animation');
    await page.goto(`${BASE}/3-algorithms/sorting/`, {
      waitUntil: 'domcontentloaded',
    });
    const controls = page.locator('.viz-controls').first();
    await controls.waitFor({ state: 'visible', timeout: 15_000 });
    const figure = page
      .locator('figure')
      .filter({ has: page.locator('.viz-controls') })
      .first();
    await figure.scrollIntoViewIfNeeded();
    await page.waitForTimeout(600);
    const box = await figure.boundingBox();
    if (!box) throw new Error('widget figure has no box');
    const clip = {
      x: Math.max(0, Math.floor(box.x)),
      y: Math.max(0, Math.floor(box.y)),
      width: Math.min(1280, Math.ceil(box.width)),
      height: Math.min(800, Math.ceil(box.height)),
    };

    await page.getByRole('button', { name: 'Play' }).first().click();

    const frames: Buffer[] = [];
    for (let i = 0; i < 14; i++) {
      frames.push(await page.screenshot({ clip }));
      await page.waitForTimeout(240);
    }
    console.log(`got ${frames.length} frames`);

    const width = 560;
    const prepared = await Promise.all(
      frames.map((f) =>
        sharp(f)
          .resize(width)
          .ensureAlpha()
          .raw()
          .toBuffer({ resolveWithObject: true }),
      ),
    );
    const frameHeight = prepared[0].info.height;
    await sharp(Buffer.concat(prepared.map((p) => p.data)), {
      raw: { width, height: frameHeight * frames.length, channels: 4 },
      animated: true,
    })
      .webp({ quality: 44, effort: 6, loop: 0, delay: 240 })
      .toFile(`${OUT}/widget.webp`);

    await browser.close();
  } finally {
    stop();
  }

  await writeFile(
    `${OUT}/README.md`,
    'Generated by `pnpm readme:media`. Do not edit by hand.\n',
  );
  console.log('done');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
