import { defineCollection, z } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

/**
 * Starlight already owns `title`, `description`, `tableOfContents`, `draft`, and
 * `sidebar`. Everything below is this site's own vocabulary.
 *
 * Page ordering deliberately uses Starlight's native `sidebar.order` rather than
 * a custom `order` field. Starlight sorts the autogenerated sidebar by that
 * field and nothing else, so a custom field would mean either declaring the
 * position twice (and watching the two drift apart) or wrapping the schema in a
 * transform — which erases the collection's inferred types everywhere they are
 * consumed. One native field, fully typed, is the better trade.
 */
export const collections = {
  docs: defineCollection({
    loader: docsLoader(),
    schema: docsSchema({
      extend: z.object({
        difficulty: z.enum(['foundational', 'core', 'advanced']).optional(),

        /**
         * `stub` — converted from a notebook, not yet rewritten to depth.
         * `draft` — rewrite in progress.
         * `complete` — satisfies the full page spine; enforced by `lint:spine`.
         *
         * Stubs ship with a visible banner, so the site can be public and honest
         * at the same time.
         */
        status: z.enum(['stub', 'draft', 'complete']).default('stub'),

        /** Page ids (e.g. `2-data-structures/binary-trees`) this page assumes. */
        prereqs: z.array(z.string()).default([]),

        tags: z.array(z.string()).default([]),

        /**
         * Which languages the page's code blocks are written in. Sections 1–6
         * are Python and TypeScript; the engineering sections need the
         * languages the work is actually done in — SQL for the data pages, HCL
         * for Terraform, YAML for pipelines and Kubernetes, shell for
         * everything with a CLI.
         */
        languages: z
          .array(
            z.enum([
              'python',
              'typescript',
              'javascript',
              'sql',
              'bash',
              'hcl',
              'yaml',
              'csharp',
            ]),
          )
          .default(['python', 'typescript']),

        /**
         * Which job roles this page belongs to. Sections are organised by
         * domain, so a role is a *path across* them — `roles` is what makes
         * those paths derivable rather than hand-listed. Tagging a page
         * `[ai, backend]` puts it on two reading paths and costs nothing.
         */
        roles: z
          .array(z.enum(['ai', 'fullstack', 'frontend', 'backend', 'cloud', 'data']))
          .default([]),

        /** Summary shown on section cards, e.g. { insert: 'O(log n)' }. */
        complexity: z.record(z.string(), z.string()).optional(),

        updated: z.date().optional(),

        /** Provenance — which notebook or note this page was built from. */
        sources: z.array(z.string()).default([]),
      }),
    }),
  }),
};
